# Generated by Django 2.2.17 on 2020-12-27 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_orders_delivery_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('item_name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('due_date', models.CharField(max_length=30)),
                ('orders_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Orders')),
            ],
        ),
    ]
