# Generated by Django 2.2.17 on 2020-12-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201227_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=12.0, max_digits=6),
            preserve_default=False,
        ),
    ]
