# Generated by Django 2.2.17 on 2020-12-28 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_customer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='billing_address',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='first_name',
            new_name='purchaser_name',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='address',
            new_name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='address',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='phone',
        ),
        migrations.AlterField(
            model_name='orders',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer'),
        ),
    ]
