# Generated by Django 2.2.17 on 2020-12-28 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201227_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='company_name',
            new_name='customer_id',
        ),
    ]
