# Generated by Django 2.2.17 on 2020-12-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('expiration', models.DateField()),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
