# Generated by Django 2.2.17 on 2020-12-28 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_invoice_paid_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('billing_address', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('due_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('paid_status', models.BooleanField()),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Invoice')),
            ],
        ),
    ]
