# Generated by Django 2.2.17 on 2020-12-28 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inventory'),
        ),
    ]
